### ISSUE TITLE
Add developer  documentation to the guide 

### ISSUE THREAD

**Issue by mspanc** [membraneframework/membrane_core#126]
We need to have a developer documentation that explain:

- [ ] what are all these controllers, dispatchers and loggers,
- [ ] what is the process architecture being used for pipelines,
- [ ] what kind of messages flow between different parts of the system,
- [ ] what is the meaning of fields in the the internal structures,
- [ ] how pulling works,
- [ ] how integration with native code is designed.

**Comment by mat-hek** [comment]
Some of these things are already documented, but as comments in the code, e.g. element's internal architecture is briefly described [here](https://github.com/membraneframework/membrane-core/blob/master/lib/membrane/core/element.ex).
