### ISSUE TITLE
Revisit pipeline and element tests

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_core#178]
Some tests for pipeline and element are a bit outdated. They should be revisited and Espec ones should be rewritten to ExUnit.

We should consider adding a code coverage tool as well

**Comment by mat-hek** [comment]
Partially done by #203

**Comment by djanda97** [comment]
Searching for `use Espec` in this repo resulted in 0 results. Does this mean that all tests were converted to ExUnit and this issue can be closed?

**Comment by mat-hek** [comment]
Yes, they were all converted
