### ISSUE TITLE
Include caps in StartOfStream event?

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/membrane_core#187]
Currently, many elements (like SWResample or GCloud) after entering `playing` mode are waiting for caps effectively treating it as StartOfStream event and implicitly assuming `caps` event will precede any buffers. My idea is to add caps field into SoS event and (optionally) replace the current Caps event with CapsChanged containing new caps.

**Comment by mat-hek** [comment]
closing in favor of #341
