### ISSUE TITLE
`handle_linking_finished` always called on all elements

### ISSUE THREAD

**Issue by kanes115** [membraneframework/membrane_core#214]
When only partial spec action is returned from callback (only concerning a subset of children), `handle_linking_finished` is called on every child element. This is due to taking children from parent's state and not from resolved links.

**Comment by mat-hek** [comment]
I believe handle_linking_finished won't be even needed if instead of sending link messages in the manner

parent->child_with_output
parent->child_with_input

we'll do

parent->child_with_output
child_with_output->child_with_input

**Comment by mat-hek** [comment]
fixed by #313
