### ISSUE TITLE
Clarify layer architecture of message processing

### ISSUE THREAD

**Issue by kanes115** [membraneframework/membrane_core#228]
We would most probably want to eradicate the need for message dispatchers and manage messages in genservers callbacks (`handle_call`, `handle_cast` and `handle_info`). This also requires changes (or removal of) `lib/membrane/helper/genserver.ex`.  This way we make message API of processes easier to grasp and get rid of situations [like this](https://github.com/membraneframework/membrane-core/blob/master/lib/membrane/core/element.ex#L129)

**Comment by mat-hek** [comment]
`Membrane.Core.Parent.MessageDispatcher` is still to be refactored out
