### ISSUE TITLE
Plugins list

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/membrane_core#257]
I think we're missing one very important thing in documentation - list of all plugins that are available. Now a potential user has to either browse the repos inside organization or check all packages published on hex from our account

**Comment by mat-hek** [comment]
We can also put experimental plugins there (marked as experimental), categorize them all, and also make a list of needed plugins in order of importance

**Comment by mat-hek** [comment]
closed as of https://github.com/membraneframework/guide/pull/44
