### ISSUE TITLE
Add child callback to handle messages from parent, replace forward action

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/membrane_core#270]
Currently, the communication between parent and child looks like this:
* child -> action `notify` -> parent -> handle_notification
* parent -> action `forward` -> child -> handle_other
We need to:
* unify the naming here
* provide a callback in child other than `handle_other` to distinguish messages from parent and from other processes
* `forward` is quite confusing when used to deliver messages that originate in parent, we need a better name for this action

## Proposed solutions

* `handle_{child,parent}_message` + `send_{child,parent}` actions
* `handle_{child,parent}_notification + `notify_{child,parent}` actions`
*  Leave `notify` and `handle_notification`, add `handle_child_notification` and `notify_child` actions

Besides the above, forward may be removed or changed into mechanism allowing routing messages without the need to implement callbacks

@mat-hek What's your take on the names? Any other suggestions?

**Comment by mat-hek** [comment]
> `handle_{child,parent}_notification` + `notify_{child,parent}` actions

seems reasonable. Regarding routing, defining routes could be a syntactic sugar over notifications.

**Comment by mickel8** [comment]
What about `handle_notification` + `notify_{child,parent}`?
I mean situation when some element can receive same notification both from parent and child and in both cases it should handle it in the same way. Not sure if this case is possible but this will simplify notation:roll_eyes:

**Comment by mat-hek** [comment]
> some element can receive same notification both from parent and child and in both cases it should handle it in the same way

That is a case only for bins, as they have children and parent, and they rather handle notifications from different components in different ways. Nevertheless `handle_notification` + `notify_{child,parent}` could work if we put `Membrane.Parent` in the `from` argument of `handle_notification` in case of a parent notification.

BTW, we should also consider whether to leave a default notification handler implemented

**Comment by mat-hek** [comment]
Another proposal is to have `send_{child, parent}` and `handle_{child, parent}_info`. After switching to `handle_info` from `handle_other` (https://github.com/membraneframework/membrane_core/issues/334#issuecomment-1028031275) this would be quite consistent, though we may consider `handle_{child, parent}_message` too.

**Comment by mat-hek** [comment]
@Qizot an action

**Comment by varsill** [comment]
In https://github.com/membraneframework/membrane_core/pull/415 I have introduced the following solution to the given problem:
1. `handle_notification/4` has become `handle_parent_notification/4`
2. Handling notification from children is now done with `handle_child_notification/3`
3. Parent's action `:forward` has been renamed to `:notify_child`
4. Child's action `:notify` has been renamed to `:notify_parent`
5. Element's action `:forward` has been renamed to `:notify_pad`

**Comment by bblaszkow06** [comment]
@varsill 

> 5. Element's action `:forward` has been renamed to `:notify_pad`

W8, what? The existing action name for forwarding incoming caps and buffers was OK and the only problem was that parent redefined the term 'forward'. Naming both actions similarly again is a step backwards.

**Comment by varsill** [comment]
Hmm, I would say that with `:notify_pad` and `:notify_children` we distinguish between these two actions (before we had exactly the same name for both of them). What's more, we precisely know where are we directing a particular piece of information. Still, I am ok with `:forward` action name and I can leave it that way.

**Comment by bblaszkow06** [comment]
> What's more, we precisely know where are we directing a particular piece of information.

The problem is that the information you, well, forward has nothing to do with notifications.

> How about `:forward_to_pad` action, to make it's name more meaningful?

I wouldn't say it's more meaningful, it's only more verbose. It can be even confusing as it forwards to all output pads, so if going the Java way, it should rather be `:forward_to_outputs`

**Comment by varsill** [comment]
Indeed.
The `:notify_pad` actions of an element has been revoked to it's original name: `:forward`
