### ISSUE TITLE
Add a custom check to credo to enforce naming unused variables everywhere

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_core#272]

**Comment by bblaszkow06** [comment]
I'd rather created a PR for credo adding the option to enforce one approach within [`Credo.Check.Consistency.UnusedVariableNames`](https://hexdocs.pm/credo/Credo.Check.Consistency.UnusedVariableNames.html)

**Comment by daniel-jodlos** [comment]
It seems that this change was just released with credo 1.6.0
