### ISSUE TITLE
Add persistent events

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_core#286]
Let's consider a case with DTLS handshake and SRTP encryption. We have SRTP encryptor, DTLS sink and some elements between them. Now, we send SRTP key via an upstream event from DTLS to SRTP. SRTP can start encrypting packets and everything works. But, if we'd like to connect more SRTP encryptors to the same DTLS sink, for example via a funnel, the newly added encryptors won't receive the SRTP key, as the event is already gone.

A solution to that may be to introduce persistent events, that will be stored in the context, and elements like funnel will have to send them to any newly added pad, like the caps.

**Comment by mickel8** [comment]
Sounds good :+1:  If we decide to introduce them we also should consider some constraints on maximal number of such events to store.

**Comment by mat-hek** [comment]
Maybe events of the same type could override one another

**Comment by mickel8** [comment]
This could be an option because in DTLS-SRTP scenario there can be multiple events of the same type each carrying different `keying material`. E.g. when we have more than one component in ICE stream

**Comment by mat-hek** [comment]
We could have a function calculating the key from the event (defaulting to event type). Then we could override events that have the same key

**Comment by mat-hek** [comment]
Moved to https://github.com/orgs/membraneframework/discussions/714
