### ISSUE TITLE
Add ability to link multiple elements within one process

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_core#293]
The reasoning behind this idea is the following:
- In most cases, we need no concurrency nor fault tolerance at the element level. Therefore, having a process for each element is actually using processes to organise the business logic, which is a bad practice.
- Message passing between elements may increase latency (to be verified).
- Message passing between elements involves either data copying (small binaries) or passing binary references between processes (large binaries). In both cases, performance is affected: directly or via sophisticated garbage collection, respectively. However, it's still to be verified how this actually impacts the performance overall.

The general problems with the proposed approach are the following:
- In many cases, we still need element-level concurrency and fault tolerance - just not between each pair of elements.
- We don't know if and how merging elements into one process would affect the performance - though based on my knowledge of beam, it should help in most cases if done reasonably.
- It will be impossible to determine an addressee of a custom message and invoke `handle_other` of the proper element
- Handling demands will still be required.
- Handling multi-pad elements will be problematic, possibly involving pad starvation protection, especially for pull pads.

My proposition of approaching this proposition is the following:
- [ ] Compare the performance of the current approach with the new approach on a sample pipeline - can be done by creating a wrapper element calling the callbacks of each internal element. Possibly check on OTP 24 JIT. Remember to check different buffer sizes and frequencies.
- [ ] Allow opt-in grouping elements within a single `ParentSpec`, but only the ones that meet the following criteria:
    - They don't implement the `handle_other` callback.
    - They are filters with exactly one input and one output pad.
    - They either work in push mode or have `auto-demand` turned on (see #285)

  I believe this will cover the majority of elements without the need to rewrite a half of the core, allowing us to validate the approach and possibly gain performance benefits in a reasonable time.
- [ ] Possibly extend grouping support for other elements or even bins.

Before taking this approach, we should implement auto-demand #285 and finish all the [currently investigated optimizations](https://github.com/membraneframework/membrane_core/pulls)

cc @membraneframework/membraneteam

**Comment by AndrzejPodo** [comment]
After thinking a while I came up with few statements that might be helpful to simplify the implementation. Probably I'm missing something as I'm quite new to `membrane_core`. Here they are:
* `push` mode should be everything what is needed between internal elements,
*  internal elements could work as a composition of `handle_process` functions (but kind of stateful composition where each function has a state),
* all processing is done by assumption on a single process so the overall time that each buffer spends inside whole group when using composition should be the same as with some more sophisticated solutions,
* at the first glance internal elements don't need `inputbuffers` as they work synchronously - they should always consume everything they have received and produce new state and output to feed next function, 
* the demand can be taken from the output pad of whole group and passed to the input pad of whole group

**Comment by mat-hek** [comment]
@AndrzejPodo that's all true, the problem is that we want to be able to use elements in both discussed scenarios, so we cannot assume they use push mode.

**Comment by AndrzejPodo** [comment]
@mat-hek I'm not sure if I understand correctly - do you mean that the same element that can work as a separate process should also work well inside a group? If so, then I think it should be possible to utilise only state and `handle_process` implementations of element and just ignore the mode of pads.

**Comment by mat-hek** [comment]
I'm afraid we cannot - that would make elements relying on demands and `handle_demand` callback misbehave. That's why I mentioned auto-demands.

**Comment by mspanc** [comment]
I think it is valid to assume that such groups can work either for `pull` or `push` elements but not both.

I don't think we need to support elements with multiple pads for now.

For push groups the scenario would be the following: wait for the first element to push the data, and then recursively pass the data to the `handle_process` function of the subsequent elements.

For pull groups the scenario would be the following: wait for the last element to demand the data, and then recursively call the `handle_demand` function of the previous elements.

That should allow to implement this with no changes to the API.
