### ISSUE TITLE
Standardize buffer timestamps fields

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/membrane_core#325]
Currently, we have a couple of elements with some timestamp support:

- https://github.com/membraneframework/membrane_h264_ffmpeg_plugin
- https://github.com/membraneframework/membrane_video_merger_plugin

They use timestamps (DTS & PTS) in buffer metadata - we need to make it a standard and include those fields in a buffer itself

**Comment by mat-hek** [comment]
That should possibly be done along with #67
