### ISSUE TITLE
[RFC] Add handle_caps_mismatch(?) callback

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/membrane_core#327]
In order to allow providing users with meaningful feedback when there's a caps mismatch on a pad, we could add a callback like `handle_caps_mismatch` or `handle_invalid_caps` to `WithInputPads` behaviour allowing to print custom messages.

The examples where this could be useful:

* MP4 Muxer that requires payloaded media streams and could suggest adding them
* Elements requiring parsed input like H264 encoder and decoder

**Comment by mat-hek** [comment]
Moved to https://github.com/orgs/membraneframework/discussions/713
