### ISSUE TITLE
Add ability to make a synchronous call to Pipeline

### ISSUE THREAD

**Issue by mickel8** [membraneframework/membrane_core#334]
Sometimes it can be useful to be able to make a synchronous call to the Pipeline e.g. to fetch some part of its state.

The task is to add ability to make such a call. 

Example API
```elixir
defmodule MyPipeline do
  use Membrane.Pipeline

  def start() do
    # ...
  end
 
  def get_counter(pid) do
    Membrane.Pipeline.call(pid, :get_counter)
  end  
  
  @impl true
  def handle_init(_opts) do
   %{:ok, {counter: 0}} 
  end  
  
  @impl true
  def handle_call(:get_counter, _ctx, state) do
    {{:ok, [reply: state.counter] ++ other_actions}, state}
  end
end
```    

This API assums addition of new action called `:reply`.
This action might but not must be returned from `handle_call`.
User can reply in another callback - to this end it might be resonable to add one more action called `:reply_to`.

As `Membrane.Pipeline` is a `GenServer` we can just wrap [GenServer.call](https://hexdocs.pm/elixir/1.12.3/GenServer.html#call/3).

Changes that should be made
1) `Membrane.Pipeline` - add `call` function that will wrap `GenServer.call` and `handle_call` callback that user will implement
1) `Membrane.Core.Pipeline` - implement callback `handle_call` and call inside it `CallbackHandler.exec_and_handle_callback`. 
`from` argument can be passed in `context` to `Membrane.Pipeline.handle_call` callback so that user will be able to reply later.
1) `Membrane.Core.Pipeline.ActionHandler` - add one more clause for  `do_handle_action` that will handle `:reply` action (and a second one for `:reply_to`?). Here we can use [GenServer.reply](https://hexdocs.pm/elixir/GenServer.html#reply/2) to reply to the call.

**Comment by mat-hek** [comment]
we could rename`handle_other -> handle_info` then
