### ISSUE TITLE
Caps description doesn't render correctly in hex docs

### ISSUE THREAD

**Issue by daniel-jodlos** [membraneframework/membrane_core#356]
It seems that some HTML - specific characters are being replaced with their HTML codes, including HTML tags
<img width="848" alt="Zrzut ekranu 2021-11-22 o 16 53 15" src="https://user-images.githubusercontent.com/20843107/142893021-ba50541c-f655-4c07-93e4-35e10ca288a2.png">

**Comment by bblaszkow06** [comment]
I had briefly investigated that one: it broke with one of the ex_doc updates as a result of changes in its deps - earmark started to escape the HTML tags by default. However, this option seems like a workaround: https://github.com/pragdave/earmark/pull/401

**Comment by Qizot** [comment]
@bblaszkow06 It is more than that. A year ago `ex_doc` switched to from `earmark` to `earmark_parser` which is a dependency of `earmark` so in this case it is not just a matter of adding the flag unfortunately. The PR changing the dependency is here https://github.com/elixir-lang/ex_doc/pull/1209

**Comment by Qizot** [comment]
Unfortunately, probably WONT FIX until https://github.com/RobertDober/earmark_parser/issues/7 moves forward :(
