### ISSUE TITLE
Add parent type which includes all CallbackContext types

### ISSUE THREAD

**Issue by mickel8** [membraneframework/membrane_core#368]
At the moment, we have separate CallbackContext type for each callback.
As an example, we have:
```elixir
t:Membrane.Bin.CallbackContext.CrashGroupDown.t/0
t:Membrane.Bin.CallbackContext.Notification.t/0
t:Membrane.Bin.CallbackContext.Other.t/0
t:Membrane.Bin.CallbackContext.PadAdded.t/0 
t:Membrane.Bin.CallbackContext.PadRemoved.t/0 
t:Membrane.Bin.CallbackContext.PlaybackChange.t/0 
t:Membrane.Bin.CallbackContext.SpecStarted.t/0
t:Membrane.Bin.CallbackContext.StreamManagement.t/0 
t:Membrane.Bin.CallbackContext.Tick.t/0
```
This makes writing function specs quite hard as we would have to specify all possible CallbackContext types.

```elixir
def my_fun(ctx :: ???)
```

The idea is to introduce parent types that will group specific CallbackContext types

```elixir
defmodule Membrane.CallbackContext do
  @type t() :: Membrane.Bin.CallbackContext.t()
    | Membrane.Element.Callback.Context.t()
    | Membrane.Pipeline.Callback.Context.t()
end

defmodule Membrane.Bin.CallbackContext do
  @type t() :: Membrane.Bin.CallbackContext.CrashGroupDown.t()
    | Membrane.Bin.CallbackContext.Notification.t()
    | Membrane.Bin.CallbackContext.Other.t()
    | etc.
end

## the same for Element, Pipeline etc.
```        

For context you can refer to  https://github.com/membraneframework/membrane_rtc_engine/pull/62#discussion_r774578357

**Comment by djanda97** [comment]
Taking a look at the documentation for `v1.0.0-rc0`, is it safe to assume that this issue is fixed?
[https://hexdocs.pm/membrane_core/1.0.0-rc0/v1-0-0-rc0.html#don-t-refer-to-callback-contexts-as-to-structs](https://hexdocs.pm/membrane_core/1.0.0-rc0/v1-0-0-rc0.html#don-t-refer-to-callback-contexts-as-to-structs)

**Comment by mat-hek** [comment]
Yes, we definitely should clean up those issues, they're a bit abandoned since we moved to jira. Thanks for helping out with this!

**Comment by djanda97** [comment]
@mat-hek
Of course! I was excited to learn about this project 😄
Are the Jira issues open to community viewing/contributions?

**Comment by mat-hek** [comment]
They are open to viewing: https://membraneframework.atlassian.net/jira/projects though the UX is very poor if you're not a team member. We're currently figuring out if there are better options.
