### ISSUE TITLE
Rename element internals to reflect better if they're handling incoming or outgoing data

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/membrane_core#371]
@mat-hek wrote: I'm going to rename this and more functions in element internals to reflect better if they're handling incoming or outgoing data in a separate PR

_Originally posted by @mat-hek in https://github.com/membraneframework/membrane_core/pull/313#discussion_r775975638_

**Comment by darthez** [comment]
The decision is to evaluate how much work it could be and depending on that make a final decision should we proceed or not.
