### ISSUE TITLE
Remove "common" types from Membrane.Pad

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/membrane_core#372]
I'm not sure if you want to include it here, but it's high time we removed those ugly "common" types
1. It adds useless jump when trying to find the typespec
1. It breaks how Keyword lists are rendered by ex_doc, here's the comparison of input_spec_t:
  
  ![image](https://user-images.githubusercontent.com/2119556/146042814-38aec6ec-5985-4de7-8d41-d53a97ab4f53.png)
  ![image](https://user-images.githubusercontent.com/2119556/146042941-c27c8271-d761-4f13-bb00-8151fe043972.png)

To avoid repetition we can use macro defined in the separate module - this seems to work on, at least on Elixir 1.13.0:
```elixir
defmodule Membrane.Pad.TypeMacros do
  defmacro common_spec_opts(name) do
    quote do
      @type unquote(name) ::
              {name_t(),
               [
                 {:availability, availability_t()}
                 | {:mode, mode_t()}
                 | {:caps, Caps.Matcher.caps_specs_t()}
                 | {:options, Keyword.t()}
               ]}
    end
  end

  defmacro common_spec_opts(name, spec) do
    quote do
      @type unquote(name) ::
              {name_t(),
               [
                 {:availability, availability_t()}
                 | {:mode, mode_t()}
                 | {:caps, Caps.Matcher.caps_specs_t()}
                 | {:options, Keyword.t()}
                 | unquote(spec)
               ]}
    end
  end
end
```

_Originally posted by @bblaszkow06 in https://github.com/membraneframework/membrane_core/pull/313#discussion_r768864448_

@mat-hek answered:
> I think it would be better to manually duplicate some options to reduce magic. I think it's out of scope though.

**Comment by djanda97** [comment]
Is this issue still valid or has it been resolved?

**Comment by mat-hek** [comment]
✅
