### ISSUE TITLE
Pad's data in context passed to Bin's callbacks may not be updated correctly.

### ISSUE THREAD

**Issue by marcinwasowicz** [membraneframework/membrane_core#373]
After investigating context structure passed to handle_element_end_of_stream in sink_bin in HLS plugin it was noticed that end_of_stream? flag is always unset for every single pad during entire element lifecycle. After discussing this finding with other team members it was concluded that this is arguably bug.

**Comment by mat-hek** [comment]
This will be fixed by #313

**Comment by mat-hek** [comment]
fixed by #313
