### ISSUE TITLE
Add option to suppress "unlinked pads" warning

### ISSUE THREAD

**Issue by agga1** [membraneframework/membrane_core#379]
In some cases, it would be good to have the option to suppress "Some static pads remained unlinked" warning, e.g here:
https://github.com/membraneframework/membrane_audio_mix_plugin/pull/15
![image](https://user-images.githubusercontent.com/25201831/149334457-332911e5-de1c-4eaa-b7c5-2722575242ff.png)
In this case there is a Bin which distributes audio mixing load between many AudioMixer elements by creating a tree of mixers. during each "handle_pad_added", new input pad is linked to some mixer, however, the output of the mixer might not be linked yet because it is unknown yet - it depends on how many inputs there will be. 
All needed linking is eventually done by the handle_stopped_to_prepared callback, so all elements all linked properly before the :playback state. Such Bin works correctly in a pipeline.

In such cases, it should be possible to suppress "unlinked pads" warning.

**Comment by mat-hek** [comment]
closed by #313
