### ISSUE TITLE
handle_stopped_to_terminating/2 is never called

### ISSUE THREAD

**Issue by varsill** [membraneframework/membrane_core#402]
`handle_stopped_to_terminating/2` is described as a part of an API in the documentation: https://hexdocs.pm/membrane_core/Membrane.Pipeline.html#c:handle_stopped_to_terminating/2
but the implementation looks as follows: https://github.com/membraneframework/membrane_core/blob/f7ff09f929d26c455cc2b3d117c8ddf428f162d3/lib/membrane/core/playback_handler.ex#L82
and this callback never gets called.
There are no tests in the membrane_core concerning that callback and in the membraneframework organization repositories I haven't found any usage of that callback, so probably it was just forgotten to be removed from the documentation in the PR which removed the functionality from the playback_handler: https://github.com/membraneframework/membrane_core/pull/237

**Comment by FelonEkonom** [comment]
Outdated since https://github.com/membraneframework/membrane_core/pull/432
