### ISSUE TITLE
Unexpected pipeline failure

### ISSUE THREAD

**Issue by swindarf** [membraneframework/membrane_core#445]
Hi everyone, I'm building a video mixer plugin that uses the hstack ffmpeg filter to merge frames. One of the functionalities is being able to switch to a different filter if one of the input pads is removed. The output of the mixer is always 16:9 full HD, so if there is only one pad the mixer only resizes the input frames.

An example that explains the mixers functionality:
- one 16:9, 10 seconds input; one 16:9, 5 seconds input -> output is the stacked inputs for 5 seconds, then the fullscreen final 5 seconds of the longer input

My test cases:
- input1: 1080p 16:9 10s, input2: 720p 16:9 5s -> works fine
- input1: 1080p 16:9 10s, input2: 240p 4:3 5s -> works fine
- input1: 240p 4:3 10s -> works fine, output is resized to 16:9 1080p
- input1: 1080p 16:9 5s, input2: 240p 4:3 10s ->  crashes after the filter switch

Last steps before the failure:
- handle_end_of_stream is called
- pad is removed from state
- filter is switched correctly 
- one payload goes into the mixer
- the mixer returns a payload of the correct size
- handle_end_of_stream returns {{:ok, [buffer: "output_buffer"]}, state}
- the pipeline freezes

The pipeline freezes and shuts down after a couple of seconds with "Reason: :shutdown"
The action returned by handle_end_of_stream seems correct to me, and this only happening for 4:3 inputs makes me wonder what could be going wrong.
Does anyone have a suggestion of what might be happening?

**Comment by DominikWolek** [comment]
I transfered this issue to the [`membrane_core`](https://github.com/membraneframework/membrane_core) - I don't think it's relevant to [`membrane_demo`](https://github.com/membraneframework/membrane_demo).

Unfortunately, I don't think we can help you without the code of the `VideoMixer`. The test itself looks fine, though.

**Comment by mat-hek** [comment]
Hi @swindarf, it may happen that the end of stream never arrives at the sink, thus the test process exits and shuts the pipeline down. Hard to say though, as the log doesn't include the actual error causing the test to fail.

**Comment by swindarf** [comment]
Thanks for the help, as you rightly said the sink never received `end_of_stream` as the stream ended while buffers where still in the queue, so I actually missed a flush function.
The prototype is working fine now. @DominikWolek as you discussed with my coworker on the membrane discord, we will open source the mixer as soon as possible.
