### ISSUE TITLE
Demand units should be taken from caps

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_core#51]
For example, demand of size _k_ should result in:
- demanding _k_ MPEG frames on pad with MPEG caps
- demanding _k_*_channels_no_ samples on pad with raw caps
- demanding _k_ bytes on pad with bytestream caps (that need to be created)

To make this usable, we should also add some demand converting functionality - each caps should export function converting _k_-element demand to equivalent size in bytes (possibly approximate)

Caps changing dynamically may introduce some problems to this approach, so place, time and way of converting sizes need to be carrefully chosen. We should also keep in mind that caps may not be present when the first demand is executed.

Demands in bytes may also need to be supported even with caps different than bytestream, for example when ringbuffer has fixed size such way would be convenient.

We should also consider making PullBuffer size declaring unit always bytes, to avoid mistakes.

**Comment by mspanc** [comment]
According to the planning meeting on 25.06.2018 it seems to be important to the end user so should be added soon but not in 0.2.0.

There's a lot of heuristics involved when trying to determine what "1 buffer" means and it needs good brainstorming before being implemented.
