### ISSUE TITLE
Buffers and demands should be cleaned up after playback -> prepare

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_core#55]
- This should not happen when switching to `paused` state if we add it in the future (#64)
- We should consider whether events should also be cleaned up (probably not)
- Race conditions when quick playback changes occur need to be avoided

**Comment by mspanc** [comment]
According to the planning meeting on 25.06.2018 seems like something that is not our first requirement. See also #64

**Comment by mat-hek** [comment]
closing in favour of #375
