### ISSUE TITLE
end_of_stream on crash group down

### ISSUE THREAD

**Issue by dmorn** [membraneframework/membrane_core#588]
We have a pipeline with many crash groups. It looks like when a crash group goes down, an end_of_stream message is delivered immediately to the input pad of the element attached to it (which is in a crash group by itself). Is this expected? We're on membrane_core v0.12.5!

**Comment by mat-hek** [comment]
Whenever a dynamic input pad is unlinked, an end_of_stream is generated (as long as a start_of_stream has arrived before). It seems that's your case too.

**Comment by dmorn** [comment]
Hi @mat-hek! This is a no-go for our pipeline. Is there a clean way to distinguish between an "upstream" end_of_stream and this one?

**Comment by mat-hek** [comment]
Currently, there's not :/ But I think we can add such information to the callback context. To work this around, you can send your custom event before the end_of_stream and handle that instead

**Comment by dmorn** [comment]
I was thinking about sending myself a message when the end_of_stream arrives. If an handle_pad_removed callback is called before the message comes, back, I'll discard it. Otherwise I'll deliver the end_of_stream. WDYT? We basically have a "dynamic input pad adapter" before each crash group so that we can isolate the different portions of the pipeline, we are not actually dynamically adding/removing pads in there if not on a crash.

**Comment by dmorn** [comment]
I agree 😉 It works though, thanks.
