### ISSUE TITLE
Membrane.Clock process is not stopped when pipeline shutdown

### ISSUE THREAD

**Issue by gBillal** [membraneframework/membrane_core#596]
I'm using `membrane_core 0.12.8`. I have a pipeline that does some work and runs periodically (say each 1 hour). When looking at the process list in phoenix live dashboard, I see this

![image](https://github.com/membraneframework/membrane_core/assets/84322223/39090a3e-d7b5-4def-8d3a-121c4ba8c10a)

A lot of Membrane.Clock processes. All the ancestors processes of most of this Clock processes are dead except for the high level supervisors started with the main application.

Note that I'm using `Pipeline.start` instead of `Pipeline.start_link` to avoid crashing the supervisor since I stop the pipeline with `terminate: :shutdown`.

**Comment by FelonEkonom** [comment]
In fact, I have just released https://github.com/membraneframework/membrane_core/releases/tag/v0.12.9 version with this fix
