### ISSUE TITLE
Create Membrane SDK

### ISSUE THREAD

**Issue by DominikWolek** [membraneframework/membrane_core#618]
The idea is to convert `membrane_gigachad` into `membrane_sdk`, that would be periodically released (once per ~3 months + after important releases?) and would contain packages' versions that are compatible with each other. With each release, we’d update & QA our demos.

User story:

As a user of Membrane, I’d like to
- know which versions of packages are compatible with each other, so that I can avoid dependency conflicts
- be able to get started with Membrane with minimal effort, so that I can check it out without installing multiple dependencies

As a Membrane developer, I’d like to detect incompatible packages so I can fix the incompatibilities early 

AC:

- First version of membrane_sdk, containing all plugins from membraneframework organisation
- membrane_sdk compiles without installing any other things on linux and mac (including livebook desktop) - requires either precompilation or ignoring native stuff that can’t compile or both 
- deps in demos updated to the versions in membrane_sdk

**Comment by DominikWolek** [comment]
https://github.com/membraneframework/membrane_gigachad/pull/2

**Comment by DominikWolek** [comment]
We've decided to merge the PR above without problematic packages with native deps. Those packages are:

- membrane_camera_capture_plugin
- membrane_ffmpeg_video_filter_plugin
- membrane_rtmp_plugin
- membrane_portaudio_plugin

SDK is not yet released, to be released after we fix problems with those plugins.

**Comment by mat-hek** [comment]
@DominikWolek camera capture, video filter and RTMP should be working now ;)
