### ISSUE TITLE
Support for streaming via stdio

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_core#627]
Allow for sending/receiving streams via standard IO. Probably should be added to membrane_file_plugin

User story:

As a Membrane user, I’d like to send/receive streams via stdio, so that I can connect the Membrane pipeline to another service, such as FFmpeg or GStreamer pipeline

**Comment by kidp330** [comment]
Filed logger issue: https://github.com/elixir-lang/elixir/issues/13313

**Comment by kidp330** [comment]
Filed cache issue: elixir-lang/elixir#13326
