### ISSUE TITLE
Add precompiled ffmpeg for arm64 architecture

### ISSUE THREAD

**Issue by DominikWolek** [membraneframework/membrane_core#658]
This feature was requested and partially contributed by the community, see: https://github.com/membraneframework/membrane_ffmpeg_swscale_plugin/pull/24

As a user of Membrane plugins, I would like for ffmpeg-based plugins to use the precompile package for arm64, so that I could use them more easily on arm64 hardware.

**Comment by DominikWolek** [comment]
- [ ] membrane_ffmpeg_swscale_plugin https://github.com/membraneframework/membrane_ffmpeg_swscale_plugin/pull/24
- [ ] membrane_ffmpeg_swresample_plugin
- [ ] membrane_ffmpeg_video_filter_plugin
- [ ] membrane_h264_ffmpeg_plugin
- [ ] membrane_rtmp_plugin

**Comment by DominikWolek** [comment]
After a quick chat with @mat-hek we decided to start working on this issue after [refactor of os deps in bundlex](https://github.com/membraneframework/bundlex/pull/111) will be merged & released

**Comment by Noarkhh** [comment]
This issue will be resolved by https://github.com/membraneframework/membrane_core/issues/661, since precompiled ffmpeg will be managed by `membrane_precompiled_dependency_provider`
