### ISSUE TITLE
Release `0.11.0` for `Membrane.UDP.Plugin` isn't published at hex

### ISSUE THREAD

**Issue by WojciechBarczynski** [membraneframework/membrane_core#665]
- version `0.11.0` on GH: https://github.com/membraneframework/membrane_udp_plugin
- version `0.10.0` on Hex: https://hex.pm/packages/membrane_udp_plugin
- version `0.10.0` in docs: https://hexdocs.pm/membrane_udp_plugin/readme.html

**Comment by mat-hek** [comment]
✅ https://hex.pm/packages/membrane_udp_plugin
