### ISSUE TITLE
Archive webrtc-server?

### ISSUE THREAD

**Issue by Nezteb** [membraneframework/membrane_core#667]
Question: Should we archive https://github.com/membraneframework/webrtc-server?

This suggestion is based on a conversation from the Discord:

> @mickel8: [webrtc-server is old signalling server that we don't use anywhere right now](https://ptb.discord.com/channels/464786597288738816/1007191990527590510/1168641873456418847)
> @Nezteb: [Is there a reason it's "old" and not used? Should that repo be archived? 😄 Is there a plan to create a "new" signalling server?](https://ptb.discord.com/channels/464786597288738816/1007191990527590510/1168674530424782918)
> @DominikWolek: [That's actually good suggestion. Afaik we only have two old demos that use it](https://ptb.discord.com/channels/464786597288738816/1007191990527590510/1168867273700810774)

**Comment by mat-hek** [comment]
@DominikWolek I'd archive the hex package as well and put a link to Jellyfish in the readme ;)

**Comment by DominikWolek** [comment]
https://github.com/membraneframework/webrtc-server/pull/14

**Comment by DominikWolek** [comment]
[Hex package](https://hex.pm/packages/membrane_webrtc_server) is retired (deprecated). Repo can be moved to labs @mat-hek

**Comment by mat-hek** [comment]
@DominikWolek done, let's mention in the readme that it's not maintained and republish the docs
