### ISSUE TITLE
Update membrane_mp4_plugin tests

### ISSUE THREAD

**Issue by FelonEkonom** [membraneframework/membrane_core#678]
Instead of checking if output file/buffers are equal to the reference value 
1) use `ffmpeg` to check if output video/audio looks or sounds the same way as the reference video/audio
2) check if the output data meets the check `byte_size(output_data) <= some_factor * byte_size(reference_data)`

@varsill add something to this list, if you have any other ideas

**Comment by varsill** [comment]
I have found a disadvantage after considering it for a moment - such an approach could result in "ffmpeg lock-in". 
As we all know, FFmpeg can handle a much broader scope of streams than the average player (with all the "best_effor_timestamp" tricks and so on), so a change in output binary that makes the stream improper (but still playable by FFmpeg) might slip away. With the current approach we can check the reference binary once on multiple players and be sure, that the output will stay exactly the same in case the tests pass.

**Comment by mat-hek** [comment]
> use ffmpeg to check if output video/audio looks or sounds the same way as the reference video/audio

This isn't trivial. Also, most of the time nothing should change in the fixtures, and for that the strict comparison works the best

> check if the output data meets the check `byte_size(output_data) <= some_factor * byte_size(reference_data)`

Where does this constraint come from?

**Comment by darthez** [comment]
Let's not do it 🖖
