### ISSUE TITLE
Unifex can't return `nil`

### ISSUE THREAD

**Issue by mickel8** [membraneframework/membrane_core#684]
Consider following spec:

```elixir
spec get_peer_cert(state) :: payload | (nil :: label)
```

when compiling with Unifex, there are two issues:
* generated function name does not include `nil` word i.e.

```c
UNIFEX_TERM get_peer_cert_result_(UnifexEnv *env) {
  return enif_make_atom(env, "");
}
```

* it returns invalid value i.e.`:""` instead of `nil`

**Comment by FelonEkonom** [comment]
According to your second issue, have you tried `return enif_make_atom(env, "nil");`?
