### ISSUE TITLE
Consider making PullBuffer size change dynamically (especially on startup)

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_core#72]
Currently PullBuffer size is configurable but fixed during playback. We should consider if it helps to adjust it basing on current demand. This is most important on change to `playing` state, because huge demands occur then, what might affect stream fluency and cause significant processor usage at the moment.

**Comment by mspanc** [comment]
According to the planning meeting on 25.06.2018 seems like something that is not our first requirement.
