### ISSUE TITLE
Documentation changes

### ISSUE THREAD

**Issue by bradhanks** [membraneframework/membrane_core#722]
I've been working my way through the Membrane.* top-level modules just to learn it better.
I'm coming across some opportunities to potentially build on the existing documentation. 

Would that benefit this project? 

I'm going through the modules so I figured I might as well while I'm in there if it is helpful.

**Comment by mat-hek** [comment]
Hi @bradhanks, sure, that would be great!

**Comment by bradhanks** [comment]
Will do! I have many drafts but nothing I'd be ready to submit before doublechecking my understanding.
