### ISSUE TITLE
Helper queue for multi-input elements

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_core#734]
The idea is to have a queue that multi-input pads could use to consume buffers at proper speed. The goal is to make mixers and muxers code simpler, more declarative and thus less error-prone.

The queue should:
- Consume buffers at equal speed from all pads, based on timestamps
- Return `pause_auto_demand` and `resume_auto_demand` actions to avoid keeping too many buffers
- Handle dynamically starting and ending streams

To verify the queue's functionality, we should use it in at least one muxer, for example in https://github.com/membraneframework/membrane_flv_plugin and mixer, for example in https://github.com/membraneframework/membrane_audio_mix_plugin

**Comment by FelonEkonom** [comment]
In progress:
 - implement basic functionalities (pop, push)
TODO:
 - specify average chunk size, expresesed in time duration
 - specify pause demand boundary in time duration
 - write benchmarks and optimize the queue

**Comment by darthez** [comment]
Let's close this one and move the idea of live queue to discussions, @FelonEkonom
