### ISSUE TITLE
GitHub action add pr to Smackore failed again

### ISSUE THREAD

**Issue by bartkrak** [membraneframework/membrane_core#749]
Add PR to Smackore project board, if the author is from outside Membrane Team failed multiple times when authors were from outside membrane team.

https://github.com/membraneframework/membrane_core/actions/runs/7827285148/job/21354800960?pr=744

**Comment by bartkrak** [comment]
Current status:
add_pr_to_smackore_board doesn't work because `gh project item-edit` throws `unknown flag: --force` even though no such flag is passed to it. This may be a GitHub-side bug. Right now  script add_pr_to_smackore_board has some part commented out so it won't crash.
I have created issue in GitHub cli repo with hope that someone also encountered this strange behaviour and will help or GitHub will fix this: https://github.com/cli/cli/issues/8759

**Comment by williammartin** [comment]
Hey @bartkrak, just coming over here from the CLI. Just so you know, this project is public and so are your workflows so I can see all the details you are redacting just by looking at your actions runs e.g. https://github.com/membraneframework/membrane_core/actions/runs/8052942839/job/21994199679

The ids aren't really secret either, there are access controls to prevent them being used without the correct permissions.

**Comment by bartkrak** [comment]
Ok, still learning.
