### ISSUE TITLE
[MP4] MP4 plugin has a test case with audio and video but the HLS playlist only lists video.

### ISSUE THREAD

**Issue by jerzywilczek** [membraneframework/membrane_core#759]
https://github.com/membraneframework/membrane_mp4_plugin/blob/8b55570faaecfa79b1eeffb4b8077b18624f1f25/test/fixtures/cmaf/muxed_audio_video/index.m3u8#L4C44-L4C48

Other than the issue mentioned in the topic, some values in the mp4 seem to be strange, e.g. the second `sidx` box in the first segment has `earliest_presentation_time = 18446744073709537000`, which does not seem right...

**Comment by Qizot** [comment]
@mat-hek `earliest_presentation_time` in the schema is represented by `:uint64` where I believe it should be `:int64`?

If you change the given time to a signed integer you get `-14616`.

**Comment by jerzywilczek** [comment]
@mat-hek didn't notice any other values, but I wasn't looking very hard.

**Comment by jerzywilczek** [comment]
@mat-hek I think other timestamps may be wrong too, don't remember anymore

**Comment by mat-hek** [comment]
@Qizot it should be unsigned according to the spec. It seems we pass a negative value there and we shouldn't.

**Comment by Qizot** [comment]
@mat-hek This [fragment](https://github.com/membraneframework/membrane_mp4_plugin/blob/8b55570faaecfa79b1eeffb4b8077b18624f1f25/lib/membrane_mp4/muxer/cmaf.ex#L715) takes DTS instead of the PTS value so here is the bug.

**Comment by mat-hek** [comment]
@Qizot unfortunately it's also somehow used for calculating durations. Changing it makes the following tests fail:

```elixir
  3) test video with partial segments should create as many partial segments as possible until reaching a key frame (Membrane.MP4.Muxer.CMAF.IntegrationTest)
     test/membrane_mp4/muxer/cmaf/integration_test.exs:215
     Assertion with <= failed
     code:  assert buffer.metadata.duration <= Membrane.Time.milliseconds(550)
     left:  1000000000
     right: 550000000
     stacktrace:
       test/membrane_mp4/muxer/cmaf/integration_test.exs:227: (test)
```

```elixir
  6) test video partial segments (Membrane.MP4.Muxer.CMAF.IntegrationTest)
     test/membrane_mp4/muxer/cmaf/integration_test.exs:170
     Assertion with < failed
     code:  assert buffer.metadata.duration < Membrane.Time.milliseconds(550)
     left:  1000000000
     right: 550000000
     stacktrace:
       test/membrane_mp4/muxer/cmaf/integration_test.exs:182: anonymous fn/3 in Membrane.MP4.Muxer.CMAF.IntegrationTest."test video partial segments"/1
       (elixir 1.15.4) lib/enum.ex:4379: Enum.reduce/3
       test/membrane_mp4/muxer/cmaf/integration_test.exs:179: (test)
```

**Comment by Karolk99** [comment]
@mat-hek, the link you referred to for the master manifest in the mp4_plugin is a hardcoded fixture from three years ago. If you look at the fixtures in the HTTP Adaptive Stream Plugin (for example, [master manifest](https://github.com/membraneframework/membrane_http_adaptive_stream_plugin/blob/master/test/membrane_http_adaptive_stream/integration_test/fixtures/muxed_av/index.m3u8)), you'll see that they include the audio codec.

**Comment by mat-hek** [comment]
Ok, so we just don't compare manifests as we focus on the m4s files, thus the outdated fixture. I'm removing it in https://github.com/membraneframework/membrane_mp4_plugin/pull/103. @jerzywilczek have a look at the HTTP adaptive stream plugin for manifest-related stuff.

**Comment by mat-hek** [comment]
Closing as https://github.com/membraneframework/membrane_mp4_plugin/pull/103. and https://github.com/membraneframework/membrane_mp4_plugin/pull/104 are merged, @jerzywilczek feel free to report more weird values :D
