### ISSUE TITLE
[membrane_file_plugin] Tests fail with elixir v1.16.0

### ISSUE THREAD

**Issue by kidq330** [membraneframework/membrane_core#774]
Since `Mix.Shell.Quiet` is not total in its functionality, the new behaviour of `Mix.install` can sometimes leak logs, making it harder to use `%Membrane.File.Sink{location: :stdout}`. In particular, the warnings that show up when compiling the `elixir-rational` library, which is a dependency of `membrane_core`.

Fixing the warnings also fixes the leaky logs encountered in file_plugin's tests (but I would expect more cases like this to crop up). I would consider to also inspect whether the leaks stem from a non-homogenous way of logging in the implementation of `Mix.install` itself. I mentioned this particular case as a side note [here](https://github.com/elixir-lang/elixir/issues/13313), but have not received an explicit response.

A PR has been opened in `elixir-rational`, let's hope it is noticed soon.

Blocks #773.

**Comment by kidq330** [comment]
I guess since the PR's destination is elixir-rational's master branch directly, it is considered to be outside the organisation 😵‍💫 linking [here](https://github.com/Qqwy/elixir-rational/pull/128) instead.

**Comment by mat-hek** [comment]
The [PR](https://github.com/Qqwy/elixir-rational/pull/128) is merged, so the tests should stop failing once we update the core to 1.1.0
