### ISSUE TITLE
[bundlex] Bundle whisper.cpp

### ISSUE THREAD

**Issue by johns10** [membraneframework/membrane_core#832]
Team,

I'd like to write some bindings to whisper.cpp using bundlex. At this point, I think the best approach is to use their makefile on the target machine to build the .so file, and use that and the .h file to run the library.

My bundlex.exs looks like this:

```
defmodule TodoApp.BundlexProject do
  use Bundlex.Project

  def project() do
    [
      natives: natives(Bundlex.get_target())
    ]
  end

  defp natives(_platform) do
    [
      test: [
        interface: [:nif],
        sources: ["main.cpp"],
        libs: ["whisper"],
        lib_dirs: ["c_src/whisper/"],
        includes: ["c_src/whisper"],
        language: :cpp
      ]
    ]
  end
end
```

I put the entire whisper proejct in c_src/whisper, and ran `make libwhisper.so` and am trying to run with that tack. I'm cribbing from the agora_sdk example for this.

**Comment by mat-hek** [comment]
Hi there, I didn't get what's the problem here, can you elaborate? Out of curiosity, why not use Whisper via Bumblebee? ;)

**Comment by johns10** [comment]
Because I'd like to use this on the client device. I haven't been able to get this to work. I have kind of bailed on this approach and am looking at elixir_make with raw make files.

**Comment by mat-hek** [comment]
Got it, that's tricky. I'm closing this then, feel free to reopen or just comment if you have any more thoughts.
