### ISSUE TITLE
[vpx_plugin] Allow requesting keyframes

### ISSUE THREAD

**Issue by Noarkhh** [membraneframework/membrane_core#840]
We can utilize a functionality provided by libvpx to force an encoder to create a keyframe. We'll do this with upstream events, allowing events down the pipeline to demand keyframes.

**Comment by Noarkhh** [comment]
Another thing that would be quick and easy is adding metadata to buffers informing whether a given frame is a keyframe or not

**Comment by mat-hek** [comment]
We can use https://hexdocs.pm/membrane_core/Membrane.KeyframeRequestEvent.html for that purpose
