### ISSUE TITLE
[Unifex] Optional `_length` addition to `[type]`s

### ISSUE THREAD

**Issue by harrisi** [membraneframework/membrane_core#877]
In some cases, I don't necessarily need a length field for every pointer. The two main use cases I've had for this is returning a pointer to a struct and using pointers to pointers.

I'm not sure what the syntax for this should look like. One option would be to highjack the pin operator:

```elixir
type foo :: %Foo{
  some_pointer: ^int
}
```

This is kind of nice, kind of not, since it uses Pascal's pointer syntax, for those of us who know Pascal (I'm sure there are dozens of us in the Elixir community ;)). It also is nice in that, by not using the list (`[]`) syntax, it does kind of imply it's not pointing to a collection of data of type `int`, but a single `int`, so the length field shouldn't be expected.

This also works with pointers to pointers. Currently I do this:

```elixir
type int_p :: %Foo{
  p: [int]
}

type int_pp :: %Foo{
  my_pointer_pointer: [int_p]
}
```

Since `[[int]]` doesn't (currently) parse correctly. I think I'd like to open a PR for that as well, but with the "lengthless" pointer option, I could do this:

```elixir
type bar :: %Foo{
  my_pointer_pointer: ^[int] # or even `^^int`, I suppose, although that has a different meaning
}
```

Anyway, that's somewhat unrelated.

I'm not sure what other syntax would make sense. Any other unary operator could be used, but I do like the Pascal syntax, personally. Another option would be to use `{int}`, which has some semantic value to it, since it's clearly a singleton, so I wouldn't expect to need a length. I don't know how I feel about this, since I kind of can imagine the tuple syntax being useful in other instances (and I already have a PR open to use tuples for explicitly-valued enums, although those are couples).

Let me know if anyone has any feelings about `^` or `{}` or some other option, or dislikes this idea entirely.

**Comment by harrisi** [comment]
I don't know how much this makes sense actually.

**Comment by FelonEkonom** [comment]
TBH I think that I see what you want to achieve on the C side of code, but I have no idea what is this supposed to mean on the Elixir side of code, I mean what would be the difference between `^[int]` and `[int]` for the Elixir code
